<?php

namespace AppBundle\Repository;

/**
 * CereriPdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CereriPdfRepository extends \Doctrine\ORM\EntityRepository
{
}
