<?php

namespace AppBundle\Repository;

/**
 * CereriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CereriRepository extends \Doctrine\ORM\EntityRepository
{
}
