<?php

namespace AppBundle\Repository;

/**
 * PontajRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PontajRepository extends \Doctrine\ORM\EntityRepository
{
}
